add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
set_languages("c++20")
set_project("KoChat")
set_version("1.1")
add_includedirs("include")
add_requires("duckdb", "asio", "ftxui")

target("client")
    set_kind("binary")
    add_files("client/client.cpp")
    add_packages("duckdb", "asio", "ftxui")

target("server")
    set_kind("binary")
    add_files("server/server.cpp")
    add_packages("duckdb", "asio")
